### ISSUE TITLE
Save button remains enabled after content is saved

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#10558]
This issue is reproducing with the XP :  [https://repo.enonic.com/repository/dev/com/enonic/xp/enonic-xp-generic/7.14.2-SNAPSHOT/enonic-xp-generic-7.14.2-20240514.140829-23.zip
](url)

**Case 1**
1. Open wizard for new site,  fill in the name input 
2. Select `SuperHero` in applications.

BUG - `Save/Saved` button remains enabled after updating a site

![image](https://github.com/enonic/app-contentstudio/assets/3728712/f8379887-8e55-481c-9f3a-ec1db4826ae9)

**Case 2** 
1. Open wizard for new shortcut , fill in the name input
2. Select a target  - image , for example 
3. Click on Save button

**BUG** - `Save/Saved` button remains enabled after saving content

![image](https://github.com/enonic/app-contentstudio/assets/3728712/f5f30505-e3ae-47ba-8e61-2998cac392fc)

**Comment by rymsha** [comment]
Strictly speaking it is a bug in frontend because in Java API there is no way to create a property without a single value.
property with `PropertySet` type is not an exception. But frontend code managed to do so via `PropertyArrayJson` class where rules are broken via internal methods.

But this bug went too far and now we have a lot of propertySets saved without a value.

I have to introduce a public method to `PropertySet` to which allows to create PropertySet without value

**Comment by rymsha** [comment]
We might have to deal with this complication later, when we need to assign UUID for each property value - since no value has no identity.
