### ISSUE TITLE
Can't reorder regions on pages

### ISSUE THREAD

**Issue by tajakobsen** [enonic/xp#1473]
Enonic will display the wrong content in the wrong region. If I
 * reorder regions in my page.xml
 * reorder regions in my html-page

**Comment by aro** [comment]
This is a known issue. Currently regions are referenced by position, and when the order is changed the handling breaks, as you say.
There is already a fix implemented, but it is not available yet because it requires some changes in the existing page and layout templates. With the fix we will reference the regions by name. That means the page and layout templates HTML must contain an attribute with the region name. Since it is a breaking change it is scheduled for the next major version: 6.0 . We will document the changes necessary with the release.
Version 6.0 is expected around June.

Thanks for the feedback.

**Comment by srs** [comment]
It's now fixed. Closing this issue.
