### ISSUE TITLE
Parts returning undefined breaks live edit

### ISSUE THREAD

**Issue by ljl** [enonic/xp#3782]
Hello again.

Concider the following part:

```
exports.get = function () {
  var content = portal.getContent();
  var result;

  if (content.data.image) {
    var imageUrl = portal.attachmentUrl({
      id: content.data.image
    });

    result = {
      body: thymeleaf.render(resolve('image.html'), {
        image: imageUrl
      })
    }
  }

  return result;
};

```

If no image is found, it returns undefined, which is fine cause i dont want it to render anything if there is no image. This works and no image is displayed. However, when creating a page template, this will always return undefined and this seems to break live edit pretty badly. I would rather have it return an error message or add a placeholder to live edit, than break the entire thing.

**Comment by aro** [comment]
The way it works now, Live Edit needs some HTML element to support the component in the page structure. So this is not a simple change.

There is a simple workaround that is to return an empty tag, only for Live Edit, and continue to leave it empty for live production rendering.
It's not perfect, since the empty markup might affect some styling, but should be good enough most of the times.

```javascript
exports.get = function () {
  var content = portal.getContent();
  var result;

  if (content.data.image) {
    var imageUrl = portal.attachmentUrl({
      id: content.data.image
    });

    result = {
      body: thymeleaf.render(resolve('image.html'), {
        image: imageUrl
      })
    }
  }
  
  // **********************
  if (!result && req.mode == 'edit') {
    result = { body: '<div></div>'}
  }
  // **********************
  return result;
};
```

We could maybe do this automatically for you. Just produce an empty tag when the part returns null and it is rendering in Edit mode. I will register a task and we will look into it.

**Comment by ljl** [comment]
Thanks for the quick reply Alex!

This is a decent workaround, but i hope you get around to do the proposed task as well. It would be more intuitive and less error prone :)
