### ISSUE TITLE
LiveEdit body margin overrides page body margin

### ISSUE THREAD

**Issue by ljl** [enonic/xp#3865]
Live Edit has set `body { margin:0; }` in its styles. This overrides the body margin set by the page which makes it look bad.

This can be solved by using !important, but i rather have live edit to be less intrusive.

SS:
<img width="396" alt="screen shot 2016-10-25 at 16 03 22" src="https://cloud.githubusercontent.com/assets/414079/19689138/9f22bc0a-9acc-11e6-8717-37c43eb8d4e1.png">

_all.css is live edit. main.scss is my own styles

**Comment by alansemenov** [comment]
You can solve this by applying a CSS class to your body element which would prioritize your selector over ours.

```html
<body class="main">
...
</body>
```

```css
body.main {
  margin-top: 60px;
}
```

**Comment by ljl** [comment]
Yes, there are plenty of ways to override CSS. 

However, i don't see a reason why live edit has to set margin to 0 - should it not display it as it would be in the browser and not be obtrusive?

**Comment by alansemenov** [comment]
We set ``margin: 0`` in order to override default body margin of 8px added by browsers (at least Chrome and Firefox), which is even more obtrusive than 0px. We could of course use one of the many reset stylesheets, but that would make things even more confusing.

http://stackoverflow.com/questions/13127887/html-default-body-margin

**Comment by ljl** [comment]
I know the browser has default margin. But the webpage itself would also get that default margin anyway if not set by its own styles. You are meddling with the look the page would have in the browser.

**Comment by ljl** [comment]
It is up to the page to handle browser resets (if they want to). Live Edit should only touch Live Edit spesific things.

**Comment by torlokken** [comment]
I agree with @ljl , any live edit css should be live edit specific, and never ever set styling on the HTML elements directly. App developer should not be asked to add more specificity to their markup/css to override wrongly set live edit css.
This is easily fixed with something like .live-edit__body { margin: 0 }

**Comment by alansemenov** [comment]
I'll see if we can remove it for 6.8.

**Comment by alansemenov** [comment]
Will be a part of the 6.8 release
