### ISSUE TITLE
UI changes in issue email

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#5087]
1. Instead of the blue circle with the issue creator's first name show content studio tree icon (as inline SVG)
2. Change sender name from "Issue Manager" to "Content Studio"
3. Show issue assignees inside the gray description section, above description, in the same form as in the issue dialog - as a row of black circles with initials inside.

Assignees:
(AB) (CD)...
10px padding
*Description*

4. Replace blue background of the "Show details..." button with the same black-ish color (#333) which we use in the Content Studio app header
5. Add issue# in brackets after issue name, for example *Issue "Name" (#11) was updated...*

**Comment by ashklianko** [comment]
"1. Instead of the blue circle with the issue creator's first name show content studio tree icon (as inline SVG)" - unfortunately gmail and some other email clients don't support inline svg in email , see https://css-tricks.com/a-guide-on-svg-support-in-email/ for reference.

We should rather skip this or replace creator's first name with something else.

**Comment by alansemenov** [comment]
It's ok - for mail readers that don't support SVG there will simply be nothing to the left of the issue title.

**Comment by ashklianko** [comment]
Ok!
