### ISSUE TITLE
Add missing norwegian translations

### ISSUE THREAD

**Issue by jsi** [enonic/xp#5246]
All localized phrases in phrases.properties have been localized to Norwegian (phrases_no.properties).   Still, there are some English text in the App, that have not been localized.  If you come across untranslated phrases, please enter them in comments below.

When this task is ready to be handled, please do the following:
 - Check out all comments below, but also look in the Content Studio yourself, for phrases where English is still Hardcoded.  Please replace these phrases with localization parameters in both phrases.properties and phrases_no.properties.
 - If you don't know Norwegian, just use the English text in both files, then alert @jsi when done, and he will finish the missing translations.

**Comment by Bellfalasch** [comment]
First three tabs here are set from custom app code. One from the content type itself and the other two from a lib and an app respectively. They cannot be translated yet.

**Comment by Bellfalasch** [comment]
Dependency widget (built in) not translating words "Inbound" or "Outbound".
![screen shot 2017-07-03 at 13 19 11](https://user-images.githubusercontent.com/1465598/27790784-50438268-5ff2-11e7-8e80-fb292a63b189.png)

**Comment by Bellfalasch** [comment]
When opening permissions dialog to edit them, none are translated. They still say "Can Read" and such. Also each given privilige is also not translated (still says "Read", "Write"). Also, the search bar says "Type to search" in English.
![screen shot 2017-07-03 at 13 17 23](https://user-images.githubusercontent.com/1465598/27790822-7e591a5a-5ff2-11e7-8801-80ef1a1999d1.png)

**Comment by Bellfalasch** [comment]
Open a content, edit it. Close it without saving. The prompt will come up in English.
![screen shot 2017-07-03 at 13 22 03](https://user-images.githubusercontent.com/1465598/27790854-ac43e45e-5ff2-11e7-9756-e3df058aeaeb.png)
Also, note that for these buttons the keyboard shortcuts are Y and N ... should this be kept or changed?

**Comment by Bellfalasch** [comment]
Open any content, edit it. Try to close the tab directly. This JavaScript prompt comes up.
![screen shot 2017-07-03 at 13 23 17](https://user-images.githubusercontent.com/1465598/27790902-db761f80-5ff2-11e7-9937-9d7e605a91a8.png)

**Comment by Bellfalasch** [comment]
Big one (no image added) - edit any image content. The entire form is still in English (from the very top to the very bottom, except a very minimal set of labels). At least some of these should be translated.

**Comment by Bellfalasch** [comment]
It seems that no title-tags (the small popups you get on hover) are translated. This is all over Content Studio. And perhaps not the most important ones ... but still not to be skipped.
![screen shot 2017-07-03 at 13 25 30](https://user-images.githubusercontent.com/1465598/27790968-25cec7e4-5ff3-11e7-854b-02fe6600a313.png)

**Comment by Bellfalasch** [comment]
Status on content, should it be translated? Still says "Online", "New", and such. Both in the Grid, in the Details panel, and inside when editing each content (on the button for publishing).
![screen shot 2017-07-03 at 13 26 31](https://user-images.githubusercontent.com/1465598/27790999-4921f54a-5ff3-11e7-98a6-f4000c17b2ef.png)

**Comment by Bellfalasch** [comment]
Edit a content without a page controller, activate the Page Editor. This text here is not translated.
![screen shot 2017-07-03 at 13 27 36](https://user-images.githubusercontent.com/1465598/27791035-74f48f66-5ff3-11e7-88e1-a20805ebf92e.png)

**Comment by Bellfalasch** [comment]
In "Emulator", none of the sizes are translated.
![screen shot 2017-07-03 at 13 28 30](https://user-images.githubusercontent.com/1465598/27791065-8f6f78c4-5ff3-11e7-9b87-ecfdced8f618.png)

**Comment by Bellfalasch** [comment]
Edit a page, try to add some parts.

1. The "Drop here" is still in English. (Region)
2. Context menues still in English.
![screen shot 2017-07-03 at 13 29 49](https://user-images.githubusercontent.com/1465598/27791117-cc60835e-5ff3-11e7-920d-e3eab6f22d23.png)

**Comment by alansemenov** [comment]
"More" is in english

![image](https://user-images.githubusercontent.com/11612490/27792357-b1b8305a-5ff9-11e7-9c65-f998973b50b2.png)

**Comment by ashklianko** [comment]
@jsi, added localization for LiveEdit in #5299, norwegian translation required :)

**Comment by alansemenov** [comment]
Still some issues:
1) When creating a new content, it gets #field.unnamed# in the display name, which is also shown on the browser tab
2) "You are wasting this space" in the preview panel. (I suggest performing search by ``setHtml('`` - this will reveal some classes with text still hardcoded.)
3) Statuses of content items ("New", "Online", "Offline" etc.) must also be translated. This should probably be moved to a separate task and be carefully handled, since we do a lot of comparison against statuses and it's very important that localisation affects only visual side and not the logic.
4) "Search" placeholder and "Clear" link in the grid filter panel, also all texts in BrowseFilterPanel.
5) Problems with localisation of the "Customize" text, it also overflows the context menu:
![image](https://user-images.githubusercontent.com/11612490/28031094-82668a24-65a6-11e7-9ed2-ddab2956fabd.png)
6) Types of page template in PageTemplateWidgetItemView.ts
7) ContentBrowsePanel > DependenciesSection
8) Dahsboard icon captions (I think we should send them from the backend along with the icons) and the entire XP Tour must also be translated - move this to a separate task as well.
9) When I drag a Part from the Inspect panel to the page, it says "Part" next to the DnD icon even though it says "Del" (in norwegian) inside the Inspect panel. So it's either not localised or using wrong Id
![image](https://user-images.githubusercontent.com/11612490/28032189-ea650de6-65a9-11e7-8c96-d5ea26f9175a.png)
10. Title of the "Publishing Issues" dialog

Also - important - always add translations to both english and norwegian files. Whoever will translate to norwegian should simply go through the norwegian file and translate english to norwegian instead of copy-pasting missing translations from the english file.

**Comment by ashklianko** [comment]
On it

**Comment by ashklianko** [comment]
Done everything mentioned except:
-Image form
-Dashboard icons and XP tour
-Content item statuses

Will do it in a next step, in separate issues if needed.

**Comment by alansemenov** [comment]
@jsi please translate english texts in common_no.properties and all of the phrases_no.properties files

**Comment by jsi** [comment]
Ok.  I am starting now!  😄

**Comment by jsi** [comment]
So, this task is completed, but there are several word choices I need to discuss with @sigdestad , so I will wait with closing this untill we have had a discussion.
