### ISSUE TITLE
Content query on path expects a node path instead of a content path

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5291]
Example:
When querying contents under features using the _path, "_path LIKE '/content/features/*" will work instead of "_path LIKE '/features/*"

* @runarmyklebust: Seems to be a bug. Do you confirm? Or is that the expected behaviour
* Find if this bug is a regression and since when
* Fix

**Comment by runarmyklebust** [comment]
Well, I know about the issue, and its noted in the documentation, but not ideal: 

http://xp.readthedocs.io/en/latest/developer/search/query-paths.html

To handle this we have to parse the expression for instances of "_path" and add the "/content/", which seems a bit nasty IMO, but maybe its better? It has been that way since the beginning, so in case we decide to fix it, we have to keep backward compatibility also.

**Comment by GlennRicaud** [comment]
Thanks for the explanation. I will close the issue
