### ISSUE TITLE
Handle situation where the indexes are closed before applying the setting and not opened correctly

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#5422]

**Comment by rymsha** [comment]
There are two places where indices get closed
- right before snapshot restore (because snapshot restore can only be done on closed indices)
- in management port "updateSettings" call

In both cases closeIndices call always follows by openIndices call (thanks to Java `finally` block).
Surely things can go wrong (JVM crash, system powered off, Elasticsearch overloaded and gives an error)
In all such cases automatic recovery is hard or impossible.

And recovery instructions are quite easy:
- open port HTTP 9200 of elastic
- open indices manually as described in Elasticsearch documentation https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-open-close.html
