### ISSUE TITLE
Invalid value in non-required content should not affect validity of the content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#5439]
1. start to add Double(Long, DateTime ...) contents
2. type a name , the content is getting valid, because the input is not required.
3. type not valid value in inputs.
BUG:  when not valid value has been typed, red icon appears and Publish button is getting disabled
But the content is valid in the grid and Publish button is enabled, when the content is selected

![double](https://user-images.githubusercontent.com/3728712/29110537-9df62104-7cef-11e7-907a-bc6c1c8a4175.png)

But when the input is empty
![double2](https://user-images.githubusercontent.com/3728712/29110544-a54314a8-7cef-11e7-8a7e-2789efee26c4.png)

**Comment by jsi** [comment]
What exactly is going on here?  The text is not very clear on what this issue is actually about.
If a date field contains an invalid string, the content should be invalid, no matter if the field is required or not.

**Comment by alansemenov** [comment]
@jsi No, content is valid as long as it stores valid values on the server. If user enters invalid value into a field then the field will be marked as invalid on the form, but the content will still be valid. If user attempts to save invalid value, it will not be saved, because we preserve validity of the content by removing invalid values before save. This is how it's always been (check 6.11 on QA, for example) but this behaviour was broken by some recent changes and this issue fixes it back.
