### ISSUE TITLE
Display progress of time-consuming move content action

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5661]
- Move and renaming can require a long time to perform since it has to update the meta-data of all the sub contents.
- We should display a progress dialog when moving a large amount of contents (similar to publish and delete).

**Comment by alansemenov** [comment]
It seems to work very nicely - great job, @edloidas !
There are two UI issues which we need to fix before we merge everything.

1. After some delay after the Move button is pressed, the NameAndIcon viewer of the target content item disappears and the selector becomes visible again. I don't understand why - we should see progress bar instead.

![image](https://user-images.githubusercontent.com/11612490/33180279-6fb445ac-d06c-11e7-93ad-26a32f9b3500.png)

2. When the progress bar finally appears, the text above says "Moving content to /". It should show path of the target content item instead of "/".

![image](https://user-images.githubusercontent.com/11612490/33180376-caf22cae-d06c-11e7-8953-585df4b55c91.png)
