### ISSUE TITLE
Multiple occurrences not working in macro form

### ISSUE THREAD

**Issue by aro** [enonic/xp#5884]
Currently macros only support single input elements in the form. If an input has max occurrences > 1, it will fail when the macro is processed.

To solve it we can allow repeating parameter names in the macro strings, and just add the values with the same name.

This requires fixing the parsing and serialisation for:
- Macro instructions: `[macro myField="value1" myField="value2"]`
- Macro postprocessing comments: `<!--#MACRO _name="macro" myField="value1" myField="value2"-->`

And in the `Macro` class use a `Multimap` instead of a `Map` for the parameters.

It should not affect existing macros, since the format does not change for single occurrences. It's backwards compatible.

This issue was [reported in Discuss](https://discuss.enonic.com/t/macro-with-contentselector/1344)
And there is a support issue: ticket 2243

**Comment by GlennRicaud** [comment]
The solution bothers me a bit. But I guess it is because I am too used to XML which does not allow this. 

Thinking out loud here:
Following the XML way, the solution would be to use sub elements. Which would be a first step to support ItemSets. But more complex to parse and handle.
Otherwise, another solution could be to have multiple elements values associated to a parameter in one association. Also slightly more complex to handle, but looking more correct.

But okay. Code looks good. Will test it and merge if tested successfully
