### ISSUE TITLE
Content & Node lib - Multiple filters at root level 

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5910]
The documentation says: 
`If specifying several filters on the filter object root level, the filters are joined automatically with a boolean “must” clause, meaning all filters much match.
`

Linked to #5906

After #5906, the following works:
```
contentLib.query({
    filters: {        
        boolean: {
            must: [{
                hasValue: {
                    field: "_path",
                    values: [
                        "/content/features"
                    ]
                }
            }, {
                hasValue: {
                    field: "_name",
                    values: [
                        "features"
                    ]
                }
            }]
        }        
    }
});
```

But this does not:
```
contentLib.query({
    filters:
        [{
            hasValue: {
                field: "_path",
                values: [
                    "/content/features"
                ]
            }
        }, {
            hasValue: {
                field: "_name",
                values: [
                    "features"
                ]
            }
        }]
});
```

**Comment by runarmyklebust** [comment]
I regret this ;)

There is no reason IMO to support the initial of filters on root - it only makes the filter definition a tad less verbose, while introducing an not obvious "must" joining between the elements. It will be more obvious when you have to define a proper boolean-filter instead of an implicit wrapping in boolean on the receiver side, and you will have the same functional possibilities AND its more in line with the underlying ES-implementation. What do you say sir @GlennRicaud ? I propose to change the documentation.
