### ISSUE TITLE
Inconsistencies in the Norwegian translations of UI

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp#6248]
During training I get quite a number of confused students (Norwegian speaking) due to the number of inconsistencies in the translations of Enonic XP. Some places translate names of things, like Content Studio, Part, Layout, into something Norwegian, and even if it feels odd in my opinion it is not done everywhere, so we end up with a solution that translate some instances of a name, but not all.

Perhaps this needs some decision-making on what should be kept in all languages etc? Content Studio is to me a name and should not be translated, Part component and Layout component are also names that should not be translated. But if they are, they should be translated everywhere.

Attaching a few screensshots on this.

In app overview "Layout" is translated to a word I cannot find anywhere else in the UI:
![screen shot 2018-05-15 at 12 36 34](https://user-images.githubusercontent.com/1465598/40052248-c010123e-583d-11e8-838d-523431b875a2.png)

In the Component overview, all component names are written in English only:
![screen shot 2018-05-15 at 12 37 01](https://user-images.githubusercontent.com/1465598/40052250-c02a0874-583d-11e8-865b-de634e8481ce.png)

When inserting components from the Insert tab in the Inspect Panel of the Page Editor, Layout is not translated:
![screen shot 2018-05-15 at 12 37 10](https://user-images.githubusercontent.com/1465598/40052252-c041ca36-583d-11e8-9d5c-7cbf22f75762.png)

In the Launcher the Content Studio name is translated, but not when running/using the admin tool:
![screen shot 2018-05-15 at 12 37 53](https://user-images.githubusercontent.com/1465598/40052253-c0586c96-583d-11e8-8e85-354e29263c1f.png)

When totally new to us and XP, it is very confusing that the system is littered with inconsistent translations. These where just four screenshots I took during one minute of clicking around, I'm sure there's plenty more.

Also, it would we wise to draw guidelines for all translations and translators on what is a name and should not be translated so we don't end up translating too much.

**Comment by alansemenov** [comment]
@jsi Jørgen take direct contact with Bobby about fixing inconsistent translations and - if we should fix other languages as well - send mail to the ones responsible.

**Comment by jsi** [comment]
I have reviewed all the phrases.properties files, and it appears the difference between "Innholdsstudio" and "Content Studio" is the two language codes, `app.name` and `admin.tool.displayName` .
For all languages, these are the same (Content Studio), except Norwegian and Russian, where the display name has been translated, but the app name remains in English.

For the other translations that are inconsistent, Component, Part, Layout, it actually appears as if some Norwegian translations have been made by the Belarussian team.  I am not 100% sure about this, since the phrases-files have been moved from xp-apps to app-contentstudio, so the history is hard to track.

This raises many questions:
- Are the developers aware of the difference between app name and display name?  I would maintain that app.name should only be used in logging and technical situations, and never shown in the UI, so if the Norwegian version display "Content Studio", anywhere, this is a coding error.
- Our release procedure checks for missing translations, but if language phrases are translated, or entered in English while waiting for a Norwegian translation, the check for missing translations will not find them.  Therefore, it is very important that only approved texts for each language are put in the phrases-files, by our approved translators.

But finally, we also should discuss which words should be translated, so we have an overarching standard to adhere to and do not end up in the situation Bobby describes.  -  I will call a meeting for this discussion.

**Comment by jsi** [comment]
PS: Angående kommentaren om layout ovenfor: Layout er layout på norsk og engelsk, så det er oversatt!  Utsnitte av "sett inn" dialogen ser veldig bra ut i mine øyne!  ;)

**Comment by Bellfalasch** [comment]
"Layout er layout på norsk og engelsk" - ja den er god, men på Application detail screen så står det oversatt til "Oppsett" hvilket er rart. Her burde det da stå "Layout" også. Det er disse inkosekvenser jeg tenkte på, at det ibland oversettes til X og ibland til Y og ibland til Z.

**Comment by jsi** [comment]
After discussion with Alan and Bobby, these are the guidelines for translations, on what should be translated, and what should not:
