### ISSUE TITLE
Tag content versions

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6394]
The list of versions a content has can become long rather quickly.
So if you need to rollback to a specific version before one started a "branch" of work that did not pan out, it can be difficult to find the correct old version.

If one had the ability to tag a content version with a name, it could be really easy to find that old version one is looking for...

**Comment by alansemenov** [comment]
I like this. REST API for ``getVersions`` already returns display name which is as of now set to the value of content's ``displayName`` property. What we need is a new property in content (``versionTag``) to point to instead of displayName.

![image](https://user-images.githubusercontent.com/11612490/42028213-ed35a20a-7acb-11e8-80fd-9f9d8ddff61b.png)

**Comment by sigdestad** [comment]
This is definetly interesting, but we believe it should be more like "tags/commits" in git. I.e. it could span across multiple items, and should probably be related to "publishing" of items

**Comment by alansemenov** [comment]
Will be solved with publish messages in 7.1
