### ISSUE TITLE
Migration to Java 10

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#6437]
* This task is a research task: Find potential problems with building and running Enonic XP on Java 10.
  * Example: An internal package we were using that has been removed

* Build successfully the entire distribution with Java 10
* Run it and find potential problems
* Build applications using JS ES6 code
* ...

**Comment by aro** [comment]
### Migration to Java 10 - Issues found
- XP launcher checks for Java 8 and fails. Version check should be rewritten.
- Apache Felix exceptions during startup: it seems fixed by upgrading OSGi and Apache Felix dependencies
- JDK packages in modules not included by default in JDK: java.xml.bind and nashorn. Workaround using ```--add-modules``` cmd-line param. It might need to be revisited for Java 11.
- Remove deprecated GC parameters (e.g. UseConcMarkSweepGC)
- Ignite NoClassDefFoundError, ClassNotFound exceptions: requires upgrading Ignite to latest version
- ElasticSearch errors: Requires upgrade. We will try upgrading to 2.4.6
- RESTEasy exceptions: It should work upgrading to [RESTEasy 3.5.1.Final](https://developer.jboss.org/en/resteasy/blog/2018/04/18/time-for-a-couple-of-bug-fix-releases)

**Comment by sigdestad** [comment]
Great job Alex, looking forward to get this running :-)
