### ISSUE TITLE
content-display-name-script using an optional field deletes the name

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6489]
Lets say you use
<content-display-name-script>$('tag')</content-display-name-script>

And tag is minium occurences="0", aka its optional.

When I first create the content I write a displayName and save.
Everything is fine.

Later I come back to change the content, and the displayName gets deleted, so when I click save the content now has a red icon and is unnamed.

**Comment by sigdestad** [comment]
How is the $tag related to displayName here?

**Comment by ComLock** [comment]
I have abandoned that app. The bug is probably still valid, but I guess very few people will ever run into it.

**Comment by pmi** [comment]
Ok, I finally managed to get rid of last error by clearing m2 caches, rebuilding xp, updating repo gradle to require 7.0.0-SNAPSHOT libs and rebuilding it as well.

But, it works as expected for me 😉 
Field tag updates displayName if not empty only, but doesn't affect it otherwise.

PS. Give me access to the repo if you need my 7.0 fixes to test it.
