### ISSUE TITLE
Homogenous schema files

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#6556]
Our different schemas use different "root" elements to hold form-items. I.e. config, items, form etc. We must use a single consistent wrapper element, i.e. <schema> instead. Also update the xsd accordingly

**Comment by GlennRicaud** [comment]
Is that a 7.0 modification?
And also do we really want this? Because these have some common elements yes but they also differ
For example content type schemas have sub elements "super-type", "is-abstract",...

**Comment by sigdestad** [comment]
This task relates to the element inside each component that now has different names i.e. "form", "config" "items" etc, not the root element of each XML file itself.
For example content type is today:
`<content-type>
  <form>...</form>
</content-type>`

We want to replace the form element with `<schema>`

Also, we should use the opportunity to make sure the XML is consistent in terms of code style.

**Comment by GlennRicaud** [comment]
I read the description too quickly. Thanks for the clarification.

So from a read of the XSD model:
There are 3 types (not talking about the naming here):
* formItems: A sequence of formItem (input, inline-mixin, fieldSet, itemSet, optionSet)
* form: An extension of formItems without any additional element. The difference is semantic. My guess from its usage is that "form" is used as this ROOT "formItems"
* config: A sequence of anything. Used for input config for example.

The schemas do mix the names "items", "form" and "config" and the types.
It seems to me that the original idea was (and the goal of this issue) that
* "items" must be of type "formItems"
* "form" must be of type "form"
* "config" must be of type "config"


Current situation and planned fixes:

* Used as "form":
"site" has an element "config" of type "form". -> Fix naming
"contentType" has an element "form" of type "formItems". -> Fix type
"mixin" has an element "items" of type "formItems". -> Fix naming and type (I can understand the confusion here since a mixin is in the end included in a form.)
"xdataType" has an element "items" of type "formItems". -> Fix naming and type
"layoutDescriptor" has an element "config" of type "form". -> Fix naming
"pageDescriptor" has an element "config" of type "form". -> Fix naming
"partDescriptor" has an element "config" of type "form". -> Fix naming
"imageDescriptor" has an element "config" of type "form". -> Fix naming
"idProviderDescriptor" has an element "config" of type "form". -> Fix naming
"macro" has an element "form" of type "formItems". -> Fix type

* Used as "formItems":
"fieldSet" has an element "items" of type "formItems". -> Correct
"itemSet" has an element "items" of type "formItems". -> Correct
"optionSetOption" has an element "items" of type "formItems". -> Correct

* Used as "config":
"input" has an element "config" of type "config". -> Correct
"widgetDescriptor" has an element "config" of type "config". -> Correct. (Not sure who specified/reviewed this. Never heard of this modification or saw it in the docs).

**Comment by sigdestad** [comment]
Not sure what you mean with these two solutions Glenn? Maybe take it f2f?

**Comment by GlennRicaud** [comment]
After discussion with bwe, tsi and cwe: We go for Solution 1.

No modification of the Java descriptor classes since it is now coherent with the Java code.
The modifications are only on the schema and the parsing:
