### ISSUE TITLE
Query pathMatch function fails with minimum_should_match parameter

### ISSUE THREAD

**Issue by aro** [enonic/xp#6569]
Query pathMatch function fails with minimum_should_match parameter.

See unit tests in FindNodesByQueryCommandTest_func_pathMatch

**Comment by GlennRicaud** [comment]
In ES 1.5, we have the following ES query
```
"query": {
  "filtered": {
    "query": {
      "match": {
        "_path._path": {
          "query": "/content/superhero/authors/theme-admin",
          "minimum_should_match": "3"
        }
      }
    }
  }
}
```
This returns the 3 contents starting with '/content/superhero/authors'.
If I understand correctly, because they match '/content', '/content/superhero' and '/content/superhero/authors'.
They are ordered by scoring ('/content/superhero/authors/theme-admin' will be the first).
If minimum_should_match was not specified it would return the nodes matching '/content'

Filtered query and query filter are deprecated (https://www.elastic.co/guide/en/elasticsearch/reference/2.4/breaking_20_query_dsl_changes.html#_literal_filtered_literal_query_and_literal_query_literal_filter_deprecated)
An equivalent (recommended by ES) working for both ES 1.5 and ES 2.4 is the following:
```
"query": {
  "bool": {
    "must": {
      "match": {
        "_path._path": {
          "query": "/content/superhero/authors/theme-admin",
          "minimum_should_match": "3"
        }
      }
    }
  }
}
```
The problem is that minimum_should_match seems to now be ignored.
  https://www.elastic.co/guide/en/elasticsearch/reference/2.4/breaking_20_query_dsl_changes.html#_literal_terms_literal_query_and_filter
  https://www.elastic.co/guide/en/elasticsearch/guide/2.x/_how_match_uses_bool.html


The solution as I see it is to leave the generation untouched if minimum_should_match is not defined.
But to put this match inside a bool with an additional term check with a path value generated from the

```
"query": {
  "bool": {
    "must": {
      "bool": {
        "must": [
          {
            "term": {
              "_path._path": "/content/superhero/authors"
            }
          },
          {
            "match": {
              "_path._path": {
                "query": "/content/superhero/authors/theme-admin",
                "minimum_should_match": "3"
              }
            }
          }
        ]
      }
    }
  }
}
```
