### ISSUE TITLE
Update publish configuration

### ISSUE THREAD

**Issue by edloidas** [enonic/xp#6572]
@edloidas commented on [Tue Sep 18 2018](https://github.com/enonic/xp-distro/pull/45)

Replaced `uploadArchives` with `publish`.
Fixed `TIMEOUT` exception, when resolving dependencies.

**Comment by GlennRicaud** [comment]
Just storing this there if I need to access it later:

About the error "Cannot configure the 'publishing' extension after it has been accessed"

After reading a bit (https://discuss.gradle.org/t/apply-maven-publish-plugin-from-init-script/2460/6) -> the publishing block is a bit special.
It allows to define configuration to be executed when the publishing is accessed.
Guess1:
  Since it works like this we cannot define this publishing after it is accessed (that makes sense).
  And it seems to be accessed somewhere in the subtasks of XP (Guess this is a collateral of something else. I saw a lot of mentions that project.getProperties indirectly access publishing)
  But so if it works like this then our DefaultPlugin.configurePublishing does not have to be executed afterEvaluate (and that it is the point of this behaviour).

But then, I noticed in the Gradle user guide the following:
  https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:deferred_configuration
So it seems that they are removing this strange behaviour of publishing.
After adding the following line to the settings.gradle (We should do that since anyway this is the future behaviour)
  enableFeaturePreview('STABLE_PUBLISHING')
The error is now gone.

Guess2:
  The publishing is now a normal block.
  It is certainly accessed somewhere in the subtasks of XP but without any impact
  We can keep the existing way to configure it with afterEvaluate (they seem to recommend it too in the same user guide paragraph)
