### ISSUE TITLE
Permissions is updated in the child folder, but   'Overwrite child permissions'   checkbox was not checked and "Inherit" checkbox in child is unchecked

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#6751]
1. Add a parent folder
2. Select the folder and add child folder
3. Click the parent folder, open details panel and open `Edit Permissions` dialog
4. Uncheck the `Inherit permissions`  in the modal dialog and add  new acl- entry , 
  do not check the   'Overwrite child permissions'  and press the Apply button

Bug: permissions is updated in the child folder, but   'Overwrite child permissions'   checkbox was not checked in the parent folder. "Inherit permissions" is unchecked in the child as well

![image](https://user-images.githubusercontent.com/3728712/48609691-fcc4fd00-e994-11e8-9baf-9de16f2909f6.png)

5. Go to the `parent-wizard` , remove the "Everyone" role and add permissions for any user , 
6. Go to the child wizard again.

BUG: 
`Everyone` role is not removed in the child wizard , but permissions for the user is added  

![image](https://user-images.githubusercontent.com/3728712/48612030-d4d79880-e998-11e8-9cd7-271736b6b75f.png)

**Comment by alansemenov** [comment]
@sgauruseu This is how it's supposed to work (or at least how it's been for a very long time). I tested it in 6.15 and it works exactly the same there. If you add a new permission to a parent item and save, it will be added to its child item even if "Inherit permissions" checkbox is off for it. 

When "Inherit permissions" checkbox is off and parent permissions are updated, we merge parent permissions with children's according to default merging strategy described below:

* Default merging strategy:
* <p>
* Include all permissions that are in only one of the two ACLs, without modification.
* For entries in both ACLs, merge according to the following rules:
* - If permission is set in child entry, use the value from the child entry
* - Otherwise if permission is set in parent entry, use the value from the parent entry
* - Otherwise leave permission unset
* <p>
* Example:
* Parent: user1[+create, -modify, -publish],          user2[+create, -modify]
* Child : user1[+create, +modify, -delete],                                    user3[+create, -modify]
* ------------------------------------------------------------------------------------------------------
* Result: user1[+create, +modify, -delete, -publish], user2[+create, -modify], user3[+create, -modify]

Please update your tests accordingly
