### ISSUE TITLE
router.get does not work in an admin tool

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#6793]
@sigdestad told me to make this.

router.dispatch works and router.filter too, but when calling next in filter it never arrives at router.get

**Comment by alansemenov** [comment]
@ComLock 
This is a known issue which has already been fixed ([here's the pull](https://github.com/enonic/lib-router/pull/8)). We cannot merge the changes yet because it depends on 7.0 changes and the new version of the lib cannot be released until the 7.0 release.

Can you use site mappings instead?

**Comment by ComLock** [comment]
No you cannot use site mappings, nor router in main.js.

I'm doing a workaround inside router.filter

**Comment by alansemenov** [comment]
Will be fixed after merge of https://github.com/enonic/lib-router/pull/8
