### ISSUE TITLE
Last publisher info shown in the preview toolbar is incorrect

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp#6940]
1. Add a folder.
2. Create an user.
3.  Select the folder and add 'Can Publish' permission to the user. 
4. Do log in with the just created user, select the folder and publish it.

**BUG**:
ContentItemPreviewPanel showing that it is published by Super User, but it actually was published by a different user.

![image](https://user-images.githubusercontent.com/3728712/52788076-dd5f6e00-3070-11e9-9a09-0a38c49a2be0.png)

**On the nightly** : 

![image](https://user-images.githubusercontent.com/3728712/52789804-fae30680-3075-11e9-9828-547050806bcd.png)

**Comment by alansemenov** [comment]
[Here](https://github.com/enonic/xp/pull/6237) we made a fix to not change `modifiedTime` field when content is published, and it's correct. However, we need to update `modifier` field when we publish or unpublish since that's the field where we take the user name from in content status message ("Modified by...", "Published by...", "Unpublished by..."). Now if content is published by a different user than the one who modified it, then user name in "Published by..." will not be correct.

**Comment by alansemenov** [comment]
Ideally we need `publisher` and `lastPublished` fields.

**Comment by sigdestad** [comment]
We must not do this. Publisher is avsilable from New committ metadata, and last Published from version timestamp

**Comment by alansemenov** [comment]
@GlennRicaud can you describe how publisher name can be extracted from the latest publish commit?

**Comment by alansemenov** [comment]
@vbradnitski talk directly to @GlennRicaud to find out how to retrieve name of the last publisher.

**Comment by GlennRicaud** [comment]
As I see it there are 2 solutions.

The proper solution would be to add this information with the rest of the publish information.
Example: Have a new field "publish.publisher"
But the reason why Thomas does not want it is I guess that in some cases there will be an impact on performance during publishing: IF the content has already been published AND IF the publisher is different from the last publisher

The other solution, a bit hacky, is to reuse the fact that we have a commit when we publish which has a committer. We do not have notion of Commit in content layer so we will have to add it.

Example: a getCommitByContentId on ContentService
 - Step1: Retrieve the current version on the branch (NodeService:getActiveVersions)
 - Step2: Retrieve the commit (NodeService:getCommit)

I will create an issue

**Comment by sigdestad** [comment]
This functionality is intentional guys, we can close the issue

**Comment by sigdestad** [comment]
Also, we now have information about who published it from the commits.

**Comment by alansemenov** [comment]
There's currently no correct way to fix this except for storing publisher/last publish date together with the rest of publishing info, as was originally suggested. We cannot/will not retrieve this from the commit because commit is not linked to publishing (a commit can be anything, not just publishing).

**Comment by sigdestad** [comment]
I thought we had a commit message that said "publish" or something like that?
