### ISSUE TITLE
Html code returned from macros are nested inside a <p>-element

### ISSUE THREAD

**Issue by RF0** [enonic/xp#6972]
Tested version 6.15.6.

When inserting a macro in CKEditor, it gets nested inside a p-element, like so:
```html
<p>[font tekst="Test Macro" klasse="intro"/]</p>
```

- If the macro return [html that is allowed inside a p-element,](https://stackoverflow.com/questions/9852312/list-of-html5-elements-that-can-be-nested-inside-p-element) it gets nested below the surrounding p-element.

- If the macro return html that is not allowed inside a p-element, f.ex. a div, it returns a empty p-element followed by the div.

- If the macro return html that is partially allowed inside a p-element, it keeps the html that is allowed inside the p-element, and puts the remaining html below the surrounding p-element.

For example if the macro returns

```html
<span><h1>My heading</h1></span>
```

the rendered html will be

```html
<p><span></span></p>
<h1>My heading</h1>
```

This is a problem because the content is not rendered the way it is supposed to with css rules, when the html cannot be determined in front. If it is nescessary that the macro gets generated inside a wrapper element, it should not be a p-element, it should be an element that is more suitable for grouping, like a span-element.

Sounds like something like this is happening, but havent looked into if this is exactly the same scenario:
https://stackoverflow.com/questions/29562393/ckeditor-plugin-insert-fake-element-add-unwilling-p-tags-before-and-after?rq=1
<img width="483" alt="screen shot 2019-03-01 at 12 38 39" src="https://user-images.githubusercontent.com/951293/53636760-900eff00-3c21-11e9-8cf1-fdb208b89cf0.png">

**Comment by alansemenov** [comment]
@RF0 It's not a macro that adds `<p></p>` wrapping, it's CKEditor that makes sure that any element in the root is wrapped inside `<p>` tag. To test, write any text, then set cursor at the end of the line and insert a macro (so that it's on the same line as the text). 

That's how CKE works and there's no way to override this. They used to have a config to replace wrapping `<p>` with `<div>` but they deprecated it since `<div>` is a subject of conflict with custom CSS even more than `<p>`.
