### ISSUE TITLE
lib-repo.rename

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7101]
Lets say it takes 1 day to populate a repo with 10Million nodes from some external resource.

The next time the "sync" is run. There's probably a bunch of new stuff, and a bunch of old stuff that should be removed.

On way to remove old nodes is to keep a list of old and new ids in memory and diff them.
However if the dataset is too big you might get memory issues, etc.

Also deleting many nodes is very slow. (I guess this is a stronger argument for this feature)

So instead of keeping stuff in memory I would like to.

1. Let the current repo stay alive while
2. A new repo is beeing populated from scratch
3. Issue a rename current->toBeDeleted
4. rename new->current
5. delete toBeDeleted

If 3 and 4 could be one atomic, "0 downtime" command, that would be perfect.

Is such a thing even possible/feasible with our current model?

**Comment by sigdestad** [comment]
To support this, we need to rewrite how blobs and indexes in ES are named. A solution for your problem is to create a name placeholder for the repo in your app, and then simply point this to a new repo when you want things to change... So basically. for each collection you may at any time point this to a repo i.e. collectionname-1, then change to point to collectionname-2 repo later.

Closing this for now
