### ISSUE TITLE
accents gives different results (when it should not due to asciifolding)

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#7115]
These give different results
fulltext('from', 'diare', 'OR', 'standard')
fulltext('from', 'diaré', 'OR', 'standard')

https://github.com/enonic/lib-yase/issues/57

**Comment by GlennRicaud** [comment]
"standard" does not have asciifolding.
"document_index_default" does

**Comment by GlennRicaud** [comment]
Your problem is that you are using the "standard" analyzer.

In Enonic XP 6, you could specify analyzer per document that were used for fulltext.
For issues or contents, this one is "document_index_default" (which has ascii folding).
When you created your nodes you did not set an analyzer, so it took the the "standard" one.

In Enonic XP 7, there is no more analyzer per document. So it will always be "document_index_default"

So two solutions for me:
Solution 1: You update the indexconfig of your nodes to have this analyzer  "document_index_default"
Solution 2: You wait for / upgrade to Enonic XP 7

**Comment by GlennRicaud** [comment]
Note to self:
Default analyzer taken for fulltext in 6.15: fulltext_search_default (identical to "document_index_default")
Thus the need to use 'standard' in the queries of ComLock

**Comment by GlennRicaud** [comment]
@ComLock I think it is possible to do set the analyzer, even though I have never tried it myself. It is just not documented

```
"_indexConfig": {
       "analyzer": "document_index_default"
        "default": {
            "decideByType": true,
            "enabled": true,
            "nGram": false,
            "fulltext": false,
            "includeInAllText": false,
            "path": false,
            "indexValueProcessors": []
        },
        "configs": []
    }
```

Should workd

**Comment by ComLock** [comment]
@GlennRicaud 

In Enonic XP 7.0

diare gives 3 results
while diaré gives 0

So the "bug" is still present in Enonic XP 7.0

**Comment by GlennRicaud** [comment]
Have you removed standard?

**Comment by ComLock** [comment]
When I remove "standard" it works :)

I guess this issue can be closed now?
