### ISSUE TITLE
Serialize/Deserialize System Dumps straight into/from archive

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#7312]
Currently dumps are written to disk and then you have to archive it. In most cases you archive it anyway.

Now when doing dumps + archiving you use more disk space than necessary. It would be advantageous to by default dump dumps straight into an archive.

Then you should obviously be able to restore dumps straight from archive as well.

**Comment by rymsha** [comment]
There are a few issues with implementation:

1. during the dump metadata is already streamed into tar archive, while (at the same time) blob-store files are written on disk directly. 
so when we want to write 
open zip stream 
  open tar stream
    write metadata file to tar stream
 write blob-store file to zip <- this won't work because we still have an opened tar file inside zip   

To overcome this issue I need to 
- either write meta into temporary file (so it should be enough disk space for two compressed versions of meta file)
- or stream blobs independently after metadata tar is ready. (basically scroll via database twice which is slower)

2. We share blob files between versions. For every new blob-file there is a check if it is already on the disk. Streams naturally don't have such ability.
To overcome this issue I need to 
- either store every blob key in memory (but then there is little to no point in streaming)
- or dump entire blob-store (this doesn't work well with includeVersions=false and maxVersions settings)

3. Restore has a special handling of old dump versions. It is implemented by reading contents and OVERRIDING existing files with updated versions. With metadata files it is even worse as restore creates temporary tar files right in dump folder. Such approach simply does not work well with compressed archives. So the only option (without rewriting everything) is to prohibit updates on zipped dupms.

**Comment by rymsha** [comment]
Documentation notes for feature

new parameter for dump endpoint  `zip` - dump straight to zip file in dump folder
new parameter for load endpoint  `zip` - dump straight from zip file in dump folder

`zip` parameter is incompatible with `upgrade`. If upgrade is required for zip exception will be thrown.

Old dump folder compressed into zip can be loaded as well. But zip filename and root dump folder in it should be equal (`dump-01-01-2020.zip` should contain `dump-01-01-2020` folder)
