### ISSUE TITLE
Add user string data encoding to prevent XSS attacks

### ISSUE THREAD

**Issue by edloidas** [enonic/xp#7626]
Add proper character encoding, before presenting data to the user and before saving that data on the server.

**Comment by rymsha** [comment]
I went through XP code as well as default apps and found no evidence of strings written directly into html or js blocks (without encoding)

XP also provides common.sanitize function which quite aggressively removes unsafe characters

Do you have anything in mind which can be improved, because I can't find it.

frontend TS is another story, but we have separate tasks for it.

**Comment by rymsha** [comment]
Oh. I finally found a few places.

**Comment by alansemenov** [comment]
Frontend issues are fixed in other epic tasks. Closing this.
