### ISSUE TITLE
ES7 Search Index: Init separate index per branch.

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/xp#7663]
In order to be able to have two and more nodes with the same NodeId in the different branches for the search index, we need to do the following changes:

- add `nodeid` and `branch` properties for search index.
- generate `_id` based on `UUID_<branch-name>`
- replace search by `id` on search by `nodeid`

**Comment by sigdestad** [comment]
Remember that we frequently use getById from ES, this will not work if we store id's as regular fields (to my knowledge)?

**Comment by rymsha** [comment]
@sigdestad

- it is ES7, and this is currently investigation "to make things to work". Not yet necessary fast. Fastest probably would be to create search-index-per-branch. We will look into it.

- thinks work with "regular" indexed fields almost same way as they work with _id. There is a "huge" difference between _id and other fields: _id is guaranteed to be unique in ES7 - but it doesn't affect search performance in our case (because our field also generated unique)

**Comment by rymsha** [comment]
@sigdestad maybe you meant that _mget won't work? Hopefully we don't use it on search index. But It is replaceable with should query for now

**Comment by sigdestad** [comment]
As far as I know, we are depending on ES unique ess for our own Keys to work as well

**Comment by vbradnitski** [comment]
Discussed with @GlennRicaud, will create new search-index per branch.

**Comment by GlennRicaud** [comment]
Might have to check if there are Queries that were expecting both to be in the same repository though
