### ISSUE TITLE
Jetty returning 200 on 8080 when cluster-provider not healthy

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp#7692]
Version: 7.1.2

If elasticsearch service-provider is unhealthy, jetty will still work on 2609. That is ok, but for port 8080, it causes some confusion and complexity for monitoring since its always returning status 200 (for any path) and no content is checked. 

To reproduce; start up sandbox, remove indices, store new content - the cluster will go to state red, now, try to access port 8080, expects e.g 503

**Comment by rymsha** [comment]
I'm little bit skeptical about it. How would app-alive work in this case?

**Comment by sigdestad** [comment]
We don't know how it behaved in this case, but it should fail when running queries against a red cluster? Site (though LB) somehow was still serving a 200 ok blank page

**Comment by rymsha** [comment]
Reason for this issue is Cluster health-check that turns off Elasticsearch client when ES is unhealthy. But everything what jetty serves on port 8080 depend on Elasticsearch client presence. There is a ServletFilter that expects at lest error page to exist (in order to ernder an error) - but even that does not exist and ServletFilter does nothing -> "This is fine!" Jetty returns 200 with an empty page.

**Comment by rymsha** [comment]
#8219 removes Cluster health-check. Hence this issue is obsolete.
