### ISSUE TITLE
The underscore path returns the main page

### ISSUE THREAD

**Issue by poi33** [enonic/xp#8148]
If you go to an url in the underscore path it will return the main site. 
Example: enonic.com/_/foobarisnowadeveloperterm
Or https://www.tine.no/_/somethinggoinghere

**Comment by sigdestad** [comment]
Should have returned 404

**Comment by rymsha** [comment]
problem is that there is no `EndpointHandler` for "somethinggoinghere" or "foobarisnowadeveloperterm" (`EndpointHandler` subclasses take care of urls with `/_/`). Since none if found request falls to PageHandler that renders default! page.

We either need a "catch-all" EndpoinHandler (but would it be able to render 404?)
Or PageHandler need to know about magic `/_/` string (I don't like it, but maybe that's the only way to render 404 pages)

Another small observation
https://github.com/enonic/xp/blob/092ddf139c792a3437b1c553e15ff8a1ab0ab95f/modules/portal/portal-api/src/main/java/com/enonic/xp/portal/handler/BaseSiteHandler.java#L57
it should  be `repoSubPath` instead of `baseSubPath`

**Comment by sigdestad** [comment]
This is a "built in" feature of the entire xp rendering engine, so no problem that core controllers know about this.
