### ISSUE TITLE
Trim down the system dumps

### ISSUE THREAD

**Issue by poi33** [enonic/xp#8188]
We have more and more clients that have 5000 content (*2 master/draft)
And now 150000 content in the audit log. 
All of this is archived zipped and downlouded every dump. 

Could XP ignore audit log? 
Only dump master or draft? 
Possibility to select what projects to include in the dump?

**Comment by rymsha** [comment]
This more of an epic

- audit-log often not needed when the dump is made. so we may want to provide an option to exclude it (keep only empty surrogate in the dump?)

**Comment by sigdestad** [comment]
I would rather opt for supporting a per repo dump, possibly dump with exclude repos option as well?

**Comment by rymsha** [comment]
I see less of an issue excluding audit-log from the dump (because it is a mandatory repository). So exclusion would only mean - copying no data.
For generic repositories exclusion would mean changing system-repo metadata, which is still (probably) possible but certainly requires more work.
Otherwise I have no problem with this feature.

**Comment by rymsha** [comment]
Let's not forget YAGNI principle.

**Comment by alansemenov** [comment]
This requires implementing a feature of creating a dump per repo. This is already in our roadmap.

**Comment by rymsha** [comment]
> Only dump master or draft?

It is peanuts, as it is a tiny bit of information inside branches index.

**Comment by alansemenov** [comment]
We have a task in the backlog for being able to dump a specific repository. Cleanup of audit log can be done with built-in schedule starting from XP 7.7.
