### ISSUE TITLE
Can we add Norwegian language analyzer in elastic search? 

### ISSUE THREAD

**Issue by poi33** [enonic/xp#8189]
Currently searching for "søme" results in "some".
<img src="https://user-images.githubusercontent.com/3340349/86026705-0d25d080-ba30-11ea-84e9-ec18793c43d9.png" width="400">

Can we add some code controlling what language analyser is used?
or set a configuration for default analyser on the server? 

(from slack https://enonic-community.slack.com/archives/C73JLM8E7/p1593436615059300)

**Comment by sigdestad** [comment]
This is due to asciifolding, and also enables search hits from some - > søme

**Comment by rymsha** [comment]
As I can read it from Slack, it is a feature request to disable ascii-folding for certain cases.

#6496, for instance, discusses an opposite case.

Ascii-folding plays important role in multilingual search world:
- it allows to index mixed-language content.
- it allows people without "native" keyboard to still search.
- it mitigates typos (think of other languages).

So content studio does benefit from ascii-folding.

Norwegian analyzer, actually 2 of them + alias, are there and turned on.

But it may appear a bug, because when I was ready to suggest searching on a correct field with specific analyzer (after selection appropriate content language) , I noticed that only `_alltext` got "templated" variant `_alltext._stemmed_no`. All data fields don't get analyzed without asciifolding filter.

**Comment by sigdestad** [comment]
I don't remember - do we index both aciifolded and original value? If we are, such search requirements could be eliminated by dropping asciifolding at query time?

**Comment by rymsha** [comment]
> do we index both aciifolded and original value

It depends. For instance, Lets take Site content with displayname `test` which has data.description field with text `svøm`. Its language is set to `no`.

We and up with full text searchable fields
```
{
  "_source": {
    "_name._analyzed": [
      "test"
    ],
    "displayname._analyzed": [
      "test"
    ],
    "data.description._analyzed": [
      "svøm"
    ],
    "_alltext._analyzed": [
      "test",
      "test",
      "IN_PROGRESS",
      "svøm"
    ],
    "_alltext._stemmed_no": [
      "test",
      "test",
      "IN_PROGRESS",
      "svøm"
    ]
  }
}

```
`_analyzed` fields are fulltext ascii-folded. 
_stemmed_no are fulltext _not_ ascii-folded and special language analyzer is applied (this is why this feature request is "incorrect" - we already have Norwegian analyzer)

But for some reason `_stemmed_no` dynamic field is only applied on `_alltext`. - IMO data fields should also get their `_stemmed_no` search fields. But it will inflate index! So we should be careful about this change and make measurements first.

> such search requirements could be eliminated by dropping asciifolding at query time?

No. Analyzer applied at index time - this is why it can search so fast.

**Comment by sigdestad** [comment]
We could possibly solve this by enable "asciifolding" true/false on a per project level.. asciifolding is primarily made to support search across multiple languages.

**Comment by alansemenov** [comment]
This is supported as stated above. We are missing some working examples in the docs which we are adding now.
