### ISSUE TITLE
query hasType filter

### ISSUE THREAD

**Issue by ComLock** [enonic/xp#8589]
Similar to the hasValue filter I would like a hasType filter
https://developer.enonic.com/docs/xp/stable/storage/filters#hasvalue
```json
hasType: {
  "field": "fisk",
  "types": [
    "string",
    "geodata"
  ]
}
```

**Comment by rymsha** [comment]
There is no such thing as geodata in XP (maybe you meant geopoint?) and almost everything can be string.

Unfortunately specification is too sparse to continue.

What is your usecase?

**Comment by ComLock** [comment]
string and geopoint where just examples we have more:

https://developer.enonic.com/docs/xp/stable/api/lib-value
binary
geoPoint
geoPointString
instant
localDate
localDateTime
localTime
reference

Usecase it make filters to only query nodes where a certain field is of a specific type.
For instance if different nodes contain the same field, but that field has different types in different nodes.
And the query result frontend presentation code only expects and handles a geopoint, it's bad to give it an array of dates.

**Comment by alansemenov** [comment]
@rymsha is it technically possible to do this using value types?

**Comment by rymsha** [comment]
Types of fields are not indexed. There is no way to search for specific type.
In practice it is not often when same filed has "geoPoint" type in one document and "localDate" in another.
In order to support `hasType` we would have to add an extra index, so everyone would have to pay extra (index requires more Storage and RAM) for not-so-often used  functionality.

- Ones who need mixed types could introduce another filed to their documents.
- In case of occasional mixed type it is best to filter them out after search is done.

**Comment by ComLock** [comment]
I can understand this, and I have sorta solved it by doing index time valueType validation.

Another idea would be to allow the programmer to select which features to enable for a repo.

Then the programmer could make choice between speed and functionality

**Comment by alansemenov** [comment]
Good that you solved it. Closing the issue
