### ISSUE TITLE
Support display name expression in content list API

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#8713]
Content type schema supports (via `display-name-expression` field) [an expression](https://developer.enonic.com/docs/xp/stable/cms/content-types#display_name_expressions) which enables dynamic generation of the displayName field based on other fields of the same content type in the Content Wizard form.

Implement a new field called `list-title-expression` in content type schema which will generate display name specifically for the `content/list` API (used to display items in the Content Studio grid).

If the field specified in expression is not found or null, replace it with an empty string.

Limit the number of allowed fields to `displayName` + all properties inside `data` (assuming that we can extend the allowed fields later on if needed).

So for example, if I have this schema of content type _Author_ with defined `<list-title-expression>`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<content-type>
  <display-name>Author</display-name>
  <super-type>base:structured</super-type>
  <description>Create authors to be selected on blog posts</description>
  <config>
    <list-title-expression>${data.name} (${data.email})</list-title-expression>
  </config>
  <form>
    <input type="TextLine" name="name">
      <label>Name</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <input type="TextLine" name="email">
      <label>Email</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <input type="TextLine" name="website">
      <label>Website</label>
      <occurrences minimum="0" maximum="1"/>
    </input>
    <input type="HtmlArea" name="bio">
      <label>Bio</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
  </form>
</content-type>
```

then content items of the type `Author` will look like this in the Content Grid:

![image](https://user-images.githubusercontent.com/11612490/112172779-4a04a980-8bf5-11eb-830f-91371ee4567e.png)

Handle non-existing fields and null values.

**Comment by sigdestad** [comment]
Nice description, but how about making this a content-studio specific configuration?

**Comment by sigdestad** [comment]
Also, I guess it would be nice to use DisplayName as fall ack?

**Comment by alansemenov** [comment]
I don't fell comfortable having two fields for display name expressions structured differently. The original one is also content-studio specific (as is input type's allowContentType and so on). We should discuss restructuring all such configs.

**Comment by sigdestad** [comment]
Allowcty is not CS spesific, even if current implementation is. Agree on dsn expression. Lets go with your approach, but find a better name :=)

**Comment by alansemenov** [comment]
> find a better name

any suggestions? `display-name-expression-list` sounds like a list of expressions. 

the key difference from the existing `display-name-expression` is that this is not something that will be generated on the fly on the client. so maybe it shouldn't have "`expression`" in its name at all. `display-name-macro`?

**Comment by sigdestad** [comment]
It is still generated on the fly? How about list-title-expression?

**Comment by alansemenov** [comment]
Nice one, updated the description

**Comment by rymsha** [comment]
Why `display-name-expression` can't be used in the list?

Where exactly this expression should be evaluated, if not on client?

**Comment by sigdestad** [comment]
Display name is basically the content title, as you would present it to a customer.
When working in content studio, editors frequently have other needs - i.e. our customer sleipner imports thousands of products from a source, and then uses these as content items. However, they are very familiar with their product identifiers that are something like "234/xs-3". When searching for products they need to see this information instantly in order to know they are dealing with the right product.

As such, list-title is a different beast from display-name, and it is not something we actually store - only use it in list presentations of content studio.

This must be processed and generated before the JSON data is returned from the server (could be computed from any field), and to content studio (so stricktly speaking it's a pure content studio thing, but I guess it could be useful in other scenarios as well).
