### ISSUE TITLE
Management port returns 403 when no authentication is provided

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp#8804]
403 implies that you are authenticated but not authorized, it should return 401

**Comment by rymsha** [comment]
There is a similar case
https://github.com/enonic/xp/issues/6900

Yes, https://tools.ietf.org/html/rfc2616 got obsolete
so now we should try to follow https://tools.ietf.org/html/rfc7231

That actually ref to
https://tools.ietf.org/html/rfc7231#section-6.5.3 and 
https://tools.ietf.org/html/rfc7235#section-3.1

But 401 MUST send a `WWW-Authenticate` header... sure but it requires some non-trivial code to implement correctly (mind you #8668)
So, what's exactly gets broken for you when 403 is sent instead of 401?

**Comment by gbbirkisson** [comment]
I figured this out when I was trying out reactive authentication in OkHttp:

```
When reactive authentication is requested by an origin web server, the response code is 401 and the implementation should respond with a new request that sets the "Authorization" header
```
