### ISSUE TITLE
BranchService cache contains invalid value after index fail

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#8833]
NodeStorageServiceImpl: 
- version and branch records remain after index failing. (could not be a bug)
- BranchService cache doesn't evict a value for failed node path.

**Comment by rymsha** [comment]
It is likely that after #9205 we don't need this cache. For instance if we use primary search preference and refresh.

**Comment by rymsha** [comment]
BranchService cache represents what is stored in branch (storage) index, but not in search index - this is expected.

It is unfortunately not that easy to remove cache - as it mitigates duplicate paths problem on single server instances. https://github.com/enonic/xp/issues/9061#issuecomment-1411151341

Problem with dyssynchronization between storage and search is more generic, for instance #10448 .

Closing, because described problem is not a problem - and other similar issues exist.
