### ISSUE TITLE
Improve starting of GraalJS on OSGI

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/xp#9016]
Improve starting of GraalJS on OSGI

**Comment by rymsha** [comment]
If we choose run XP on GraalVM #9238, then we don't need to do anything.

Bundling GraalJS as an OSGi bundle appeared to be difficult, as graal.js requires a few 3rd party dependencies, uses a lot of "guesswork" based on class existence (via `Class.forName`) to find best available implementation and requires access to a few JVM internal implementations (for instance `jdk.internal.reflect.CallerSensitive`). I didn't manage to get JVM TI interface to be used either (due to some Classpath/Classloader complications), so js was only running in interpreter mode.

It is also possible to put graal.js into framework `/lib` folder and specify in system.properties `org.osgi.framework.system.packages.extra=org.graalvm.polyglot,org.graalvm.polyglot.proxy`. I didn't run such setup in jvm-ti mode yet.

**Comment by rymsha** [comment]
Not needed as we run on GraalVM #9238
