### ISSUE TITLE
Improve reliability of CheckNodeExistsCommand

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#9205]
#9061 Describes a set of reasons why nodes with the same name can appear. Biggest issue is that there is a "check before create" - very race prone appear, but we can't deal with it right now.

Another reason is that `CheckNodeExistsCommand` checks existence of a node 
- without refreshing the index (and since we use search - 1s refresh delay applies)
- checks only data in local replica (where data may not have been replicated to yet)
- does check in two steps: first searches for node path in `search` index, then gets `NodeBranchEntry` by id from `branch` index.

Improvements for BranchService (used by CheckNodeExistsCommand):
- use only one search query on `branch` index. It is possible to get all necessary info from there. This way we don't depend on refresh of `search` index
- refresh branch index (or just all indices) when checking
- use `_primary` preference

**Comment by rymsha** [comment]
Other fixes:
- since we always use single shard, shard routing is unnecessary and confusing. (BTW, there are a few aggregation queries that assume only-single-shard per index.) In XP routing needed only for parent/child index and even there we just spoof it (we set nodeId.toString value just to bypass elasticsearch check for routing field.  We remove routing wherever possible.
-
