### ISSUE TITLE
"Enonic XP started" message is missing from log

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp#9658]
We used to output this line after XP has started: "Started Enonic XP in 11207 ms", now the final line looks like this "- Listening on ports [8080](xp), [4848](management) and [2609](monitoring)". This confuses users as to wether XP has started or not.

Re-introduce the "Started.." message after the listening message. This makes it clear for everyone that XP has actually started.

**Comment by rymsha** [comment]
It is not missing, actually. it may appear earlier as there is no ordering for OSGi services.

**Comment by sigdestad** [comment]
I thought it was possible to define dependencies between bundles? I.e. a bundle that starts after Jetty to output this?

**Comment by rymsha** [comment]
no, OSGi bundles have no dependencies.

**Comment by rymsha** [comment]
We have been discussing it before  https://github.com/enonic/xp/issues/8119#issuecomment-636368757

**Comment by sigdestad** [comment]
And there it says you will add a "bogus dependency" to fix order of events?

**Comment by rymsha** [comment]
1. The message is not missing. It just shown earlier. The issue description is incorrect.
2. Suggested "fixes" won't help.
3. Bogus dependency was added in the fix for #8119 for correctness. In this case behavior is correct.
4. It is not true that startup of Jetty indicates fully started XP. In fact that this message appears some services are still missing (for instance standard-id-provider is not accessible for a few more milliseconds). 

What exactly indicates fully started XP is undefined. 
Moreover, it is probably not possible to define because based on configuration some services may be deactivated and never start. 
Also services start asynchronously.

**Comment by rymsha** [comment]
Since our services are dynamic it is not possible to say when exactly XP is "fully started". We can only tell that XP now requested all micro-services to start
