### ISSUE TITLE
Add type definitions for Request and Response

### ISSUE THREAD

**Issue by edloidas** [enonic/xp#9742]
Add `Request` and `Response` types under the `lib-portal` types.

Page requests doesn't have contextPath

**Comment by ComLock** [comment]
It would be nice if Request headers keys are stricter than string so code will be future proof for HTTP/2.

[8.1.2.6](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.6).  Malformed Requests and Responses

   A malformed request or response is one that is an otherwise valid
   sequence of HTTP/2 frames but is invalid due to the presence of
   extraneous frames, prohibited header fields, the absence of mandatory
   header fields, or the inclusion of uppercase header field names.

**Comment by ComLock** [comment]
https://github.com/enonic/lib-react4xp/blob/master/src/main/resources/types/Request.d.ts
https://github.com/enonic/lib-react4xp/blob/master/src/main/resources/types/Response.d.ts

**Comment by ComLock** [comment]
I wonder how many times I've done this :)
https://github.com/enonic/app-explorer/blob/master/src/main/resources/types/Request.d.ts

**Comment by ComLock** [comment]
Many :)
https://github.com/enonic/lib-explorer/blob/master/src/main/resources/lib/explorer/types/Request.d.ts
https://github.com/enonic/lib-explorer/blob/master/src/main/resources/lib/explorer/types/Response.d.ts

**Comment by ComLock** [comment]
Nope
<img width="423" alt="Screenshot 2023-04-14 at 14 42 25" src="https://user-images.githubusercontent.com/118847/232046521-bf39a5a7-ebac-4a9d-b6ff-795b2770d995.png">

**Comment by ComLock** [comment]
I keep forgetting there is no such thing as lowercasestring in typings yet.

**Comment by ComLock** [comment]
`Lowercase<StringType>`
https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#lowercasestringtype

**Comment by ComLock** [comment]
Here we go again :)
https://github.com/enonic/lib-static/blob/master/src/main/resources/lib/enonic/static/types/Request.d.ts
https://github.com/enonic/lib-static/blob/master/src/main/resources/lib/enonic/static/types/Response.d.ts

**Comment by ComLock** [comment]
I think what needs to be done here is find some real life examples to test the Request and Response types against.
