### ISSUE TITLE
Dsl Term query doesn't work with uppercase

### ISSUE THREAD

**Issue by vbradnitski** [enonic/xp#9970]
```
{
  "term": {
    "field": "displayName",
    "value": "Header"
  }
}
``` 

does not find anything

**Comment by rymsha** [comment]
This happens because XP calls `.tolowerCase()` on every value set in search index. 
`term` DSL uses `term` ES query - it does not analyze the string and can never find any string with uppercase letters.
- we may reconsider how we index values in XP8, but for now we have to lower-case values before searching them

Additionally localDate and localTime need special formatting before search for almost the same reason - XP applies special format for them when storing in search index.
